### ISSUE TITLE
HostFS ?

### ISSUE THREAD

**Issue by lukasmrtvy** [axibase/nmon#4]
Hello,
I found docker image: https://hub.docker.com/r/axibase/nmon/,
For what are you using -v /:/rootfs:ro ? 
It means that you have compiled your own nmon with prefixed path where nmon looks for data?

Iam pretty sure that nmon can collect data from host layer with these parameters. 
--pid=host
--net=host
--privileged

But i dont know anything about /hostfs/ prefixed path.

Thanks

**Comment by rodionos** [comment]
@muhahacz, I believe we arrived at this setting so that file system paths are correctly processed by the `JFSFILE` section.

**Comment by muhahacz** [comment]
So basically are you using /rootfs only just for os-release and lsb-release?
https://raw.githubusercontent.com/axibase/dockers/nmon/entrypoint.sh

**Comment by rodionos** [comment]
The /etc/release is necessary for nmon to be able to populate config sections in the header.
